### ISSUE TITLE
Update from 0.5 to 0.6 not possible (DeploymentUriDifferent)

### ISSUE THREAD

**Issue by Shrekmachine** [Feincraft/Finepilot#2]
[QS1GL9L8.log](https://github.com/Feincraft/Finepilot/files/10999800/QS1GL9L8.log)

**Comment by Feincraft** [comment]
Thank you for the feedback.
Version 0.7 will come with the ability to update.
This repo was created for testing purposes, I'll publish a new link to submit issues in the future.

**Comment by Shrekmachine** [comment]
Still, pretty cool, Ilya
